name: workflow_api_fix
on:
  push:
    branches:
      - "bugfix/*"

jobs:
  validate_fix_design:
    runs-on: ubuntu-latest
    name: Validate is fix design
    steps:
      - uses: devniel93/fix-design@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}